Configuracion:
    TmpUrl: app/tmp/rutas.php
    ConfigUrl: config/rutas.yml
    OtraRuta: pitos
    
    idiomas: es,ca,en,fr,it
    estilo: iso
    
    HOME_dev: http://localhost/MyT/
    HOME: http://www.google.com/
    
    Seguridad: 1
