Gestor:
    tablas: productos,categorias,subcategorias
    n_listados: 1

Campos:
    productos: id,nombre,idcategorias
    categorias: id,nombre,idsubcategorias 
    subcategorias: id,nombre
    dependientes: productos.idcategorias:categorias|id|nombre@categorias.idsubcategorias:subcategorias|id|nombre  

    tab_productos: id|oculto|int,nombre|nomral|string,idcategorias|depe|int,des|normal|string
    tab_categorias: id|oculto|int,nombre|nomral|string,idsubcategorias|depe|int
    tab_subcategorias: id|oculto|int,nombre|nomral|string
    
    trad_productos: nombre,des
    trad_categorias: nombre
    trad_subcategorias: nombre
