Gestor:
    tablas: productos,categorias,subcategorias
    n_listados: 1

Campos:
    productos: id,nombre,idcategorias
    categorias: id,nombre,idsubcategorias 
    subcategorias: id,nombre
    dependientes: productos.idcategorias:categorias|id|nombre@categorias.idsubcategorias:subcategorias|id|nombre  


    tab_productos: id|oculto|int,nombre|nomral|string,idcategorias|depe|int,des|area|string,opciones|select|string,activo|select|int,fecha|date|fecha
    tab_categorias: id|oculto|int,nombre|nomral|string,idsubcategorias|depe|int
    tab_subcategorias: id|oculto|int,nombre|nomral|string
    
    trad_productos: nombre|normal|string,des|area|string
    trad_categorias: nombre|normal|string
    trad_subcategorias: nombre|normal|string

Select:
    opciones: productos.opciones*1|Opcion 1, 2|Opcion 2,3|Opcion 3@prductos.activo*1|Sí,0|No


IMG:   
    IMGpatron: p,75,50,50,0|m,100,200,100,0|g,100,125,200,1
    IMGdir: src/images/fotos
    IMGdirMuestra: src/images/fotos/m/m_
    IMGtablas: productos
