Gestor:
    tablas: productos,categorias,subcategorias
    n_listados: 1

Campos:
    productos: id,nombre,idcategorias
    categorias: id,nombre,idsubcategorias 
    subcategorias: id,nombre
    dependientes: productos.idcategorias:categorias|id|nombre@categorias.idsubcategorias:subcategorias|id|nombre  
