ruta_uno:
    url: pato/dos
    controller: Index::index2
    
    
ruta_dos:
    url: POLKAXY
    controller: Index::indexpolka  

ruta_tres:
    url: pluma
    controller: Pluma::po

ruta_cuatro:
    url: pupa
    conroller: Pupa::pa    
