Index:
    url:
    controller: Index::index
    permiso: 0

IndexIdioma:
    url: home/{lang:locale}
    controller: Index::index
    permiso: 0
      
ruta_uno:
    url: pato/dos/{lang:locale}/{pagina:int}
    controller: Index::index2
    permiso: 5

Gestor_editar_anidados:
    url: gestor/editar-anidado/{tabla:string}/{id:string}/{idanidado:string}
    controller: Gestor::editaranidado
    permiso: 5

Gestor_eliminar_anidados:
    url: gestor/eliminar-anidado/{tabla:string}/{id:string}/{idanidado:string}/{tablaanidado:string}
    controller: Gestor::eliminaranidado
    permiso: 5


Gestor_ineratra_anidados:
    url: gestor/insertar-anidado/{tabla:string}/{id:string}
    controller: Gestor::insertaranidado
    permiso: 5

Gestor_editar_txt_img:
   url: gestor/editar-txt-imagen/{tabla:string}/{idreg:int}
   controller: Gestor::editartxtimg
   permiso: 5 

Gestor_editar_txt_img_prin:
   url: gestor/editar-txt-imagen-prin/{tabla:string}/{idreg:int}
   controller: Gestor::editartxtimgprin
   permiso: 5 

Gestor_eliminar_img:
   url: gestor/eliminar-img/{tabla:string}/{idimagen:int}/{idreg:int}
   controller: Gestor::eliminarimg
   permiso: 5 

Gestor_editar:
   url: gestor/editar/{tabla:string}/{id:int}
   controller: Gestor::editar
   permiso: 5 


Gestor_editar_idioma:
   url: gestor/editar-idioma/{tabla:string}/{id:int}/{idiomareg:string}
   controller: Gestor::editaridioma
   permiso: 5 


Gestor_editar_idioma_accion:
   url: gestor/editar-idioma-accion/{tabla:string}/{id:int}/{idiomareg:string}
   controller: Gestor::editaridiomaccion
   permiso: 5 
   

Gestor_editar_accion:
   url: gestor/editar-accion/{tabla:string}/{id:int}
   controller: Gestor::editaraccion
   permiso: 5 
   
Gestor_buscador:
   url: gestor/buscador/reultado
   controller: Gestor::buscador
   permiso: 5   
   

Gestor_nuevo:
    url: gestor/crear-nuevo/{tabla:string}
    controller: Gestor::crear
    permiso: 5

Gestor_nuevo_accion:
    url: gestor/crear-nuevo-accion/{tabla:string}
    controller: Gestor::crearaccion
    permiso: 5   

Gestor_eliminar:
    url: gestor/eliminar/{tabla:string}/{id:int}
    controller: Gestor::eliminar
    permiso: 5 

Gestor_eliminar2:
    url: gestor/eliminar-accion/{tabla:string}/{id:int}
    controller: Gestor::eliminaraccion
    permiso: 5 
   
Gestor_listado:
    url: gestor/listado/{tabla:string}/{campo_orden:string}/{pagina:int}/{orden:string}
    controller: Gestor::listado
    permiso: 5

Gestor_subir_foto:
    url: gestor/subir-foto/{tabla:string}/{id:string}
    controller: Gestor::subirfoto
    permiso: 5
    

Gestor_index:
    url: gestor/{lang:locale}/index
    controller: Gestor::indexgestor
    permiso: 5

Gestor_index_cambio_idioma:
    url: gestor/{lang:locale}
    controller: Gestor::indexgestor
    permiso: 5
    
    


    
Gestor_index_cambio_idioma2:
    url: gestor
    controller: Gestor::indexgestor
    permiso: 5


       
   
ruta_dos:
    url: POLKAXY/{apellido:string}
    controller: Index::indexpolka
    permiso: 0

ruta_tres:
    url: pluma
    controller: Pluma::po
    permiso: 0

ruta_cuatro:
    url: pupa
    controller: Pupa::pa
    permiso: 0

login2:
    url: checking
    controller: Seguridad::check
    permiso: 0

checkout:
    url: checkout
    controller: Seguridad::checkout
    permiso: 0
