Index:
    url:
    controller: Index::index
    permiso: 0

IndexIdioma:
    url: home/{lang:locale}
    controller: Index::index
    permiso: 0
      
ruta_uno:
    url: pato/dos/{lang:locale}/{pagina:int}
    controller: Index::index2
    permiso: 1


Gestor_editar:
   url: gestor/editar/{tabla:string}/{id:int}
   controller: Gestor::editar
   permiso: 1 


Gestor_editar_idioma:
   url: gestor/editar-idioma/{tabla:string}/{id:int}/{idiomareg:string}
   controller: Gestor::editaridioma
   permiso: 1 


Gestor_editar_idioma_accion:
   url: gestor/editar-idioma-accion/{tabla:string}/{id:int}/{idiomareg:string}
   controller: Gestor::editaridiomaccion
   permiso: 1 
   

Gestor_editar_accion:
   url: gestor/editar-accion/{tabla:string}/{id:int}
   controller: Gestor::editaraccion
   permiso: 1 
   
Gestor_buscador:
   url: gestor/buscador/reultado
   controller: Gestor::buscador
   permiso: 1   
   

Gestor_nuevo:
    url: gestor/crear-nuevo/{tabla:string}
    controller: Gestor::crear
    permiso: 1

Gestor_nuevo_accion:
    url: gestor/crear-nuevo-accion/{tabla:string}
    controller: Gestor::crearaccion
    permiso: 1   

Gestor_eliminar:
    url: gestor/eliminar/{tabla:string}/{id:int}
    controller: Gestor::eliminar
    permiso: 1 

Gestor_eliminar2:
    url: gestor/eliminar-accion/{tabla:string}/{id:int}
    controller: Gestor::eliminaraccion
    permiso: 1 
   
Gestor_listado:
    url: gestor/listado/{tabla:string}/{campo_orden:string}/{pagina:int}/{orden:string}
    controller: Gestor::listado
    permiso: 1



Gestor_index:
    url: gestor/{lang:locale}/index
    controller: Gestor::indexgestor
    permiso: 1

Gestor_index_cambio_idioma:
    url: gestor/{lang:locale}
    controller: Gestor::indexgestor
    permiso: 1
    
Gestor_index_cambio_idioma2:
    url: gestor
    controller: Gestor::indexgestor
    permiso: 1


       
   
ruta_dos:
    url: POLKAXY/{apellido:string}
    controller: Index::indexpolka
    permiso: 0

ruta_tres:
    url: pluma
    controller: Pluma::po
    permiso: 0

ruta_cuatro:
    url: pupa
    controller: Pupa::pa
    permiso: 0

login2:
    url: checking
    controller: Seguridad::check
    permiso: 0

checkout:
    url: checkout
    controller: Seguridad::checkout
    permiso: 0
