ruta_uno:
    url: pato/dos/{lang:locale}/{pagina:int}
    controller: Index::index2
    
    
ruta_dos:
    url: POLKAXY/{apellido:string}
    controller: Index::indexpolka

ruta_tres:
    url: pluma
    controller: Pluma::po

ruta_cuatro:
    url: pupa
    conroller: Pupa::pa
