ruta_uno:
    url: pato/dos
    controller: Index
    
ruta_dos:
    url: POLKA 
    controller: MusicaPolka  

ruta_tres:
    url: pluma
    controller: Pluma

ruta_cuatro:
    url: pupa
    conroller: Pupa    
